<?php

/**
 * Created by PhpStorm.
 * User: Dawid
 * Date: 08.06.2017
 * Time: 22:26
 */
class OT
{
	const AUTO_WYCENA_BRAK_WYCENY = 0;
	const AUTO_WYCENA_WYCENIONE = 1;
	const AUTO_WYCENA_DODANE_DO_ZAMOWIENIA = 2;

	const RECZNA_WYCENA_PROFILU_WYCENIONE = 3;
	const RECZNA_WYCENA_PROFULU_DODANE_DO_ZAMOWIENIA = 4;

	const RECZNA_WYCENA_BLACH_WYCENIONE = 5;
	const RECZNA_WYCENA_BLACH_DODANE_DO_ZAMOWIENIA = 6;

	const AUTO_WYCENA_ZABLOKOWANA_EDYCJA = 7;
	const RECZNA_WYCENA_PROFILU_ZABLOKOWANA_EDYCJA = 8;
	const RECZNA_WYCENA_BLACHY_ZABLOKOWANA_EDYCJA = 9;

	const AUTO_WYCENA_BLACH_SINGLE_WYCENIONE = 10;

    const AUTO_WYCENA_BLACH_MULTI_KROK_1 = 12;
    const AUTO_WYCENA_BLACH_MULTI_KROK_2 = 13;
    const AUTO_WYCENA_BLACH_MULTI_ZABLOKOWANE = 14;
    const AUTO_WYCENA_BLACH_MULTI_DODANE_DO_ZAMOWIENIA = 15;

}